# permissions for end users to edit clustergithubapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clustergithubapp-editor-role
rules:
- apiGroups:
  - ghapp.tsuzu.dev
  resources:
  - clustergithubapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ghapp.tsuzu.dev
  resources:
  - clustergithubapps/status
  verbs:
  - get
