# permissions for end users to edit githubapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: githubapp-editor-role
rules:
- apiGroups:
  - ghapp.tsuzu.dev
  resources:
  - githubapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ghapp.tsuzu.dev
  resources:
  - githubapps/status
  verbs:
  - get
