// +build !ignore_autogenerated

/*
Copyright 2020 cs3238-tsuzu.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterGitHubApp) DeepCopyInto(out *ClusterGitHubApp) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterGitHubApp.
func (in *ClusterGitHubApp) DeepCopy() *ClusterGitHubApp {
	if in == nil {
		return nil
	}
	out := new(ClusterGitHubApp)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterGitHubApp) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterGitHubAppList) DeepCopyInto(out *ClusterGitHubAppList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterGitHubApp, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterGitHubAppList.
func (in *ClusterGitHubAppList) DeepCopy() *ClusterGitHubAppList {
	if in == nil {
		return nil
	}
	out := new(ClusterGitHubAppList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterGitHubAppList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterGitHubAppSpec) DeepCopyInto(out *ClusterGitHubAppSpec) {
	*out = *in
	out.PrivateKeySecretRef = in.PrivateKeySecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterGitHubAppSpec.
func (in *ClusterGitHubAppSpec) DeepCopy() *ClusterGitHubAppSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterGitHubAppSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterGitHubAppStatus) DeepCopyInto(out *ClusterGitHubAppStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterGitHubAppStatus.
func (in *ClusterGitHubAppStatus) DeepCopy() *ClusterGitHubAppStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterGitHubAppStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Installation) DeepCopyInto(out *Installation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Installation.
func (in *Installation) DeepCopy() *Installation {
	if in == nil {
		return nil
	}
	out := new(Installation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Installation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstallationList) DeepCopyInto(out *InstallationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Installation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstallationList.
func (in *InstallationList) DeepCopy() *InstallationList {
	if in == nil {
		return nil
	}
	out := new(InstallationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InstallationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstallationPermissions) DeepCopyInto(out *InstallationPermissions) {
	*out = *in
	if in.Administration != nil {
		in, out := &in.Administration, &out.Administration
		*out = new(string)
		**out = **in
	}
	if in.Blocking != nil {
		in, out := &in.Blocking, &out.Blocking
		*out = new(string)
		**out = **in
	}
	if in.Checks != nil {
		in, out := &in.Checks, &out.Checks
		*out = new(string)
		**out = **in
	}
	if in.Contents != nil {
		in, out := &in.Contents, &out.Contents
		*out = new(string)
		**out = **in
	}
	if in.ContentReferences != nil {
		in, out := &in.ContentReferences, &out.ContentReferences
		*out = new(string)
		**out = **in
	}
	if in.Deployments != nil {
		in, out := &in.Deployments, &out.Deployments
		*out = new(string)
		**out = **in
	}
	if in.Emails != nil {
		in, out := &in.Emails, &out.Emails
		*out = new(string)
		**out = **in
	}
	if in.Followers != nil {
		in, out := &in.Followers, &out.Followers
		*out = new(string)
		**out = **in
	}
	if in.Issues != nil {
		in, out := &in.Issues, &out.Issues
		*out = new(string)
		**out = **in
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = new(string)
		**out = **in
	}
	if in.Members != nil {
		in, out := &in.Members, &out.Members
		*out = new(string)
		**out = **in
	}
	if in.OrganizationAdministration != nil {
		in, out := &in.OrganizationAdministration, &out.OrganizationAdministration
		*out = new(string)
		**out = **in
	}
	if in.OrganizationHooks != nil {
		in, out := &in.OrganizationHooks, &out.OrganizationHooks
		*out = new(string)
		**out = **in
	}
	if in.OrganizationPlan != nil {
		in, out := &in.OrganizationPlan, &out.OrganizationPlan
		*out = new(string)
		**out = **in
	}
	if in.OrganizationPreReceiveHooks != nil {
		in, out := &in.OrganizationPreReceiveHooks, &out.OrganizationPreReceiveHooks
		*out = new(string)
		**out = **in
	}
	if in.OrganizationProjects != nil {
		in, out := &in.OrganizationProjects, &out.OrganizationProjects
		*out = new(string)
		**out = **in
	}
	if in.OrganizationUserBlocking != nil {
		in, out := &in.OrganizationUserBlocking, &out.OrganizationUserBlocking
		*out = new(string)
		**out = **in
	}
	if in.Packages != nil {
		in, out := &in.Packages, &out.Packages
		*out = new(string)
		**out = **in
	}
	if in.Pages != nil {
		in, out := &in.Pages, &out.Pages
		*out = new(string)
		**out = **in
	}
	if in.PullRequests != nil {
		in, out := &in.PullRequests, &out.PullRequests
		*out = new(string)
		**out = **in
	}
	if in.RepositoryHooks != nil {
		in, out := &in.RepositoryHooks, &out.RepositoryHooks
		*out = new(string)
		**out = **in
	}
	if in.RepositoryProjects != nil {
		in, out := &in.RepositoryProjects, &out.RepositoryProjects
		*out = new(string)
		**out = **in
	}
	if in.RepositoryPreReceiveHooks != nil {
		in, out := &in.RepositoryPreReceiveHooks, &out.RepositoryPreReceiveHooks
		*out = new(string)
		**out = **in
	}
	if in.SingleFile != nil {
		in, out := &in.SingleFile, &out.SingleFile
		*out = new(string)
		**out = **in
	}
	if in.Statuses != nil {
		in, out := &in.Statuses, &out.Statuses
		*out = new(string)
		**out = **in
	}
	if in.TeamDiscussions != nil {
		in, out := &in.TeamDiscussions, &out.TeamDiscussions
		*out = new(string)
		**out = **in
	}
	if in.VulnerabilityAlerts != nil {
		in, out := &in.VulnerabilityAlerts, &out.VulnerabilityAlerts
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstallationPermissions.
func (in *InstallationPermissions) DeepCopy() *InstallationPermissions {
	if in == nil {
		return nil
	}
	out := new(InstallationPermissions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstallationSpec) DeepCopyInto(out *InstallationSpec) {
	*out = *in
	out.AppRef = in.AppRef
	if in.RepositoryIDS != nil {
		in, out := &in.RepositoryIDS, &out.RepositoryIDS
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.InstallationPermissions != nil {
		in, out := &in.InstallationPermissions, &out.InstallationPermissions
		*out = new(InstallationPermissions)
		(*in).DeepCopyInto(*out)
	}
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstallationSpec.
func (in *InstallationSpec) DeepCopy() *InstallationSpec {
	if in == nil {
		return nil
	}
	out := new(InstallationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstallationStatus) DeepCopyInto(out *InstallationStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstallationStatus.
func (in *InstallationStatus) DeepCopy() *InstallationStatus {
	if in == nil {
		return nil
	}
	out := new(InstallationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateKeySecretRef) DeepCopyInto(out *PrivateKeySecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateKeySecretRef.
func (in *PrivateKeySecretRef) DeepCopy() *PrivateKeySecretRef {
	if in == nil {
		return nil
	}
	out := new(PrivateKeySecretRef)
	in.DeepCopyInto(out)
	return out
}
