name: Docker
on: 
  push:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Docker image
      uses: docker/build-push-action@v1
      with:
        username: cs3238-tsuzu
        password: ${{ secrets.GITHUB_TOKEN }}
        repository: docker.pkg.github.com/cs3238-tsuzu/ghapp-controller/controller
        dockerfile: Dockerfile
        tag_with_ref: true
        tag_with_sha: true
        push: ${{ github.event_name == 'push' }}